### ISSUE TITLE
Style (layout) not working 

### ISSUE THREAD

**Issue by rmathew1011** [TAMULib/ProjectManagement#10]
**Describe the bug**

**To Reproduce**
1. Go to 'https://labs.library.tamu.edu/products/'
2. See error

**Expected behavior**
Resolution provided by William: "is actually working and was container-fluid by design. If desired not fill the width, we just change to container".

**Screenshots**
<img width="2407" alt="PM_Screenshot" src="https://user-images.githubusercontent.com/10436265/199807417-a13b1e9b-4612-4596-8266-cf86fe0c85c7.png">

**Desktop (please complete the following information):**
 - Chrome [e.g. chrome, safari]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghost** [comment]
This is actually working and was `container-fluid` by design. If desired not fill the width, we just change to `container`.
