### ISSUE TITLE
Upgrade to latest tl_components

### ISSUE THREAD

**Issue by jcreel** [TAMULib/ProjectManagement#7]

**Comment by rmathew1011** [comment]
An issue has been created to incorporate the tl-components in ProjectManagement. 

> https://github.com/TAMULib/ProjectManagement/issues/8

**Comment by jcreel** [comment]
In order to upgrade the UI, we should bring in the latest tl-components and utilize the components to the degree possible in the app.

**Comment by rmathew1011** [comment]
PR - https://github.com/TAMULib/ProjectManagementUI/pull/131
